# Generated by Django 5.0 on 2024-01-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(default="N/A", max_length=300),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.TextField(default="company", max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="promotor_name",
            field=models.TextField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="promotror_mail",
            field=models.EmailField(default="N/A", max_length=254),
        ),
    ]
