# Generated by Django 5.0 on 2024-01-20 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profile_address_alter_profile_company_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.TextField(default="company", max_length=50),
        ),
        migrations.CreateModel(
            name="Company_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("est", models.TextField(default="20XX", max_length=4)),
                ("nature", models.TextField(default="trade", max_length=30)),
                ("status", models.TextField(default="Private Limited", max_length=20)),
                (
                    "description",
                    models.TextField(default="Business Description", max_length=50),
                ),
                ("turnover", models.TextField(default="1-1000000000", max_length=20)),
                ("employee", models.IntegerField(default="1", max_length=5)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
