# Generated by Django 5.0 on 2024-01-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_address_alter_profile_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company_profile",
            name="employee",
            field=models.IntegerField(default="1"),
        ),
    ]
