# Generated by Django 5.0 on 2024-01-20 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_company_profile_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Company_Profile",
            new_name="Company",
        ),
    ]
