# Generated by Django 5.0 on 2024-01-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_company_profile_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(default="Business Description", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="employee",
            field=models.IntegerField(default="1"),
        ),
        migrations.AddField(
            model_name="profile",
            name="est",
            field=models.TextField(default="20XX", max_length=4),
        ),
        migrations.AddField(
            model_name="profile",
            name="nature",
            field=models.TextField(default="trade", max_length=30),
        ),
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.TextField(default="Private Limited", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="turnover",
            field=models.TextField(default="1-1000000000", max_length=20),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
