# Generated by Django 5.0 on 2024-01-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_profile_description_profile_employee_profile_est_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="promotror_mail",
            field=models.EmailField(default="promotor@mail.com", max_length=254),
        ),
    ]
