# Generated by Django 5.0 on 2024-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0006_intent_sector_remove_post_country_and_more"),
        ("users", "0009_profile_auth_mail_profile_auth_mob_profile_auth_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fssai_no",
            field=models.TextField(default="N/A", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gst_no",
            field=models.TextField(default="N/A", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="iec_no",
            field=models.TextField(default="N/A", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="interested_intents",
            field=models.ManyToManyField(
                blank=True, related_name="interested_profiles", to="market.intent"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="interested_sectors",
            field=models.ManyToManyField(
                blank=True, related_name="interested_profiles", to="market.sector"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pan",
            field=models.FileField(blank=True, null=True, upload_to="documents/pan/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="pan_no",
            field=models.TextField(default="N/A", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="udyam_no",
            field=models.TextField(default="N/A", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="factorylabors",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fssai",
            field=models.FileField(blank=True, null=True, upload_to="documents/fssai/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gst",
            field=models.FileField(blank=True, null=True, upload_to="documents/gst/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="iec",
            field=models.FileField(blank=True, null=True, upload_to="documents/iec/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="udyam",
            field=models.FileField(blank=True, null=True, upload_to="documents/udyam/"),
        ),
    ]
