# Generated by Django 5.0 on 2024-02-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_profile_fssai_no_profile_gst_no_profile_iec_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="biscert",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/biscert/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="biscert_no",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="halalcert",
            field=models.FileField(blank=True, null=True, upload_to="documents/halal/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="halalcert_no",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="iso",
            field=models.FileField(blank=True, null=True, upload_to="documents/iso/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="iso_no",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="usfda",
            field=models.FileField(blank=True, null=True, upload_to="documents/usfda/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="usfda_no",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
