# Generated by Django 5.0 on 2024-02-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_registrationcertificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(default="Business Description"),
        ),
    ]
