# Generated by Django 5.0 on 2024-02-15 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_profile_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(
                choices=[
                    ("United States", "United States"),
                    ("United Kingdom", "United Kingdom"),
                    ("Canada", "Canada"),
                    ("France", "France"),
                    ("Germany", "Germany"),
                    ("Afghanistan", "Afghanistan"),
                    ("Armenia", "Armenia"),
                    ("Azerbaijan", "Azerbaijan"),
                    ("Bahrain", "Bahrain"),
                    ("Bangladesh", "Bangladesh"),
                    ("Bhutan", "Bhutan"),
                    ("Brunei", "Brunei"),
                    ("Cambodia", "Cambodia"),
                    ("China", "China"),
                    ("Cyprus", "Cyprus"),
                    ("Georgia", "Georgia"),
                    ("India", "India"),
                    ("Indonesia", "Indonesia"),
                    ("Iran", "Iran"),
                    ("Iraq", "Iraq"),
                    ("Israel", "Israel"),
                    ("Japan", "Japan"),
                    ("Jordan", "Jordan"),
                    ("Kazakhstan", "Kazakhstan"),
                    ("Kuwait", "Kuwait"),
                    ("Kyrgyzstan", "Kyrgyzstan"),
                    ("Laos", "Laos"),
                    ("Lebanon", "Lebanon"),
                    ("Macao", "Macao"),
                    ("Malaysia", "Malaysia"),
                    ("Maldives", "Maldives"),
                    ("Mongolia", "Mongolia"),
                    ("Myanmar", "Myanmar"),
                    ("Nepal", "Nepal"),
                    ("North Korea", "North Korea"),
                    ("Oman", "Oman"),
                    ("Pakistan", "Pakistan"),
                    ("Palestine", "Palestine"),
                    ("Philippines", "Philippines"),
                    ("Qatar", "Qatar"),
                    ("Saudi Arabia", "Saudi Arabia"),
                    ("Singapore", "Singapore"),
                    ("South Korea", "South Korea"),
                    ("Sri Lanka", "Sri Lanka"),
                    ("Syria", "Syria"),
                    ("Taiwan", "Taiwan"),
                    ("Tajikistan", "Tajikistan"),
                    ("Thailand", "Thailand"),
                    ("Timor-Leste", "Timor-Leste"),
                    ("Turkey", "Turkey"),
                    ("Turkmenistan", "Turkmenistan"),
                    ("United Arab Emirates", "United Arab Emirates"),
                    ("Uzbekistan", "Uzbekistan"),
                    ("Vietnam", "Vietnam"),
                    ("Yemen", "Yemen"),
                ],
                default="India",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="users.state",
                    ),
                ),
            ],
        ),
    ]
