# Generated by Django 5.0 on 2024-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_state_profile_city_profile_country_profile_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="name",
            field=models.CharField(
                choices=[
                    ("TRIPURA", "Tripura"),
                    ("UTTAR_PRADESH", "Uttar Pradesh"),
                    ("GUJARAT", "Gujarat"),
                    ("MIZORAM", "Mizoram"),
                    ("RAJASTHAN", "Rajasthan"),
                    ("KERALA", "Kerala"),
                    ("MAHARASHTRA", "Maharashtra"),
                    ("UTTARANCHAL", "Uttaranchal"),
                    ("HARYANA", "Haryana"),
                    ("MADHYA_PRADESH", "Madhya Pradesh"),
                    ("PUNJAB", "Punjab"),
                    ("HIMACHAL_PRADESH", "Himachal Pradesh"),
                    ("KARNATAKA", "Karnataka"),
                    ("ORISSA", "Orissa"),
                    ("CHHATTISGARH", "Chhattisgarh"),
                    ("BIHAR", "Bihar"),
                    ("TAMIL_NADU", "Tamil Nadu"),
                    (
                        "UNION_TERRITORY_of_DADRA_&_NAGAR_HAVELI",
                        "Union Territory Of Dadra & Nagar Haveli",
                    ),
                    ("WEST_BENGAL", "West Bengal"),
                    ("ASSAM", "Assam"),
                    ("SIKKIM", "Sikkim"),
                    ("NEW_DELHI", "New Delhi"),
                    ("GOA", "Goa"),
                    ("NCR", "Ncr"),
                    ("JAMMU_&_KASHMIR", "Jammu & Kashmir"),
                    ("ANDHRA_PRADESH", "Andhra Pradesh"),
                    ("MANIPUR", "Manipur"),
                    ("JHARKHAND", "Jharkhand"),
                    ("UTTARAKHAND", "Uttarakhand"),
                    ("NORTH_SIKKIM", "North Sikkim"),
                    (
                        "UNION_TERRITORY_OF_LAKSHADWEEP",
                        "Union Territory Of Lakshadweep",
                    ),
                    ("NEPAL", "Nepal"),
                    ("DELHI", "Delhi"),
                    ("WEST_SIKKIM", "West Sikkim"),
                    ("ANDAMAN_&_NICOBAR_ISLANDS", "Andaman & Nicobar Islands"),
                    ("MEGHALAYA", "Meghalaya"),
                ],
                default="NCR",
                max_length=100,
            ),
        ),
    ]
