# Generated by Django 5.0 on 2024-02-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_state_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="employee",
            field=models.CharField(
                choices=[
                    ("1-5", "1-5"),
                    ("6-10", "6-10"),
                    ("11-50", "11-50"),
                    ("51-100", "51-100"),
                    ("100+", "100+"),
                ],
                default="1-5",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("Proprietorship", "Proprietorship"),
                    ("Partnership", "Partnership"),
                    ("LLP", "Limited Liability Partnership"),
                    ("PvtLtd", "Private Limited"),
                    ("PubLtd", "Public Limited"),
                    ("Gov", "Government Undertaking"),
                    ("NPO", "NPO/AOP/SHG/Cooperative Societies/Trust"),
                ],
                default="Proprietorship",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="turnover",
            field=models.CharField(
                choices=[
                    ("<1M", "Less Than 1 Million Annually"),
                    ("1M-10M", "From 1M - 10M"),
                    ("10M+", "10M+"),
                ],
                default="<1M",
                max_length=20,
            ),
        ),
    ]
