# Generated by Django 5.0 on 2024-02-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_profile_est"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_state",
                to="users.state",
            ),
        ),
    ]
