# Generated by Django 5.0 on 2024-02-21 08:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_remove_profile_city_alter_profile_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="biscert",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="biscert_no",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="fssai",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="fssai_no",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="halalcert",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="halalcert_no",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="interested_intents",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="interested_sectors",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="iso",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="iso_no",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="usfda",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="usfda_no",
        ),
        migrations.AlterField(
            model_name="profile",
            name="employee",
            field=models.CharField(
                choices=[
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-100", "51-100"),
                    ("100+", "100+"),
                ],
                default="1-5",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="est",
            field=models.IntegerField(
                choices=[
                    (1980, 1980),
                    (1981, 1981),
                    (1982, 1982),
                    (1983, 1983),
                    (1984, 1984),
                    (1985, 1985),
                    (1986, 1986),
                    (1987, 1987),
                    (1988, 1988),
                    (1989, 1989),
                    (1990, 1990),
                    (1991, 1991),
                    (1992, 1992),
                    (1993, 1993),
                    (1994, 1994),
                    (1995, 1995),
                    (1996, 1996),
                    (1997, 1997),
                    (1998, 1998),
                    (1999, 1999),
                    (2000, 2000),
                    (2001, 2001),
                    (2002, 2002),
                    (2003, 2003),
                    (2004, 2004),
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                ],
                default=users.models.current_year,
                verbose_name="Establishment Year",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="turnover",
            field=models.CharField(
                choices=[
                    ("<5Cr", "Less Than 5 Crore"),
                    ("5Cr-50Cr", "From 5 Crore to 50 Crore"),
                    ("50Cr-250Cr", "From 50 Crore to 250 Crore"),
                    ("250Cr+", "More Than 250 Crore"),
                ],
                default="<1M",
                max_length=20,
            ),
        ),
    ]
