# Generated by Django 5.0 on 2024-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_remove_profile_biscert_remove_profile_biscert_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nature",
            field=models.TextField(
                choices=[
                    ("MANUFACTURER", "MANUFACTURER"),
                    ("TRADER", "TRADER"),
                    ("MANUFACTURER-EXPORTER", "MANUFACTURER-EXPORTER"),
                    ("EXPORTER", "EXPORTER"),
                    ("IMPORTER", "IMPORTER"),
                    (
                        "MANUFACTURER-EXPORTER-IMPORTER",
                        "MANUFACTURER-EXPORTER-IMPORTER",
                    ),
                ],
                default="trade",
                max_length=50,
            ),
        ),
    ]
