# Generated by Django 5.0 on 2024-01-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="item_images"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_category",
                    models.ForeignKey(
                        default="000000",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="market.category",
                    ),
                ),
                (
                    "item_industry",
                    models.ForeignKey(
                        default="00",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="market.industry",
                    ),
                ),
            ],
        ),
    ]
