# Generated by Django 5.0 on 2024-01-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
