# Generated by Django 5.0 on 2024-01-22 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_item_item_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("created_at",), "verbose_name_plural": "Items"},
        ),
    ]
