# Generated by Django 5.0 on 2024-01-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0004_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, default="kreditem.jpg", null=True, upload_to="item_images"
            ),
        ),
    ]
