# Generated by Django 5.0 on 2024-02-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0006_alter_item_image"),
        ("market", "0006_intent_sector_remove_post_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="Best used before date for perishable items",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="preferred_unit",
            field=models.CharField(
                choices=[
                    ("KG", "Kilogram"),
                    ("LBS", "Pounds"),
                    ("PCS", "Pieces"),
                    ("L", "Liters"),
                ],
                default="PCS",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="quality_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="market.category",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_industry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="market.industry",
            ),
        ),
    ]
