# Generated by Django 5.0 on 2024-03-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0007_item_available_item_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="preferred_unit",
            field=models.CharField(
                choices=[
                    ("KG", "Kilogram"),
                    ("LBS", "Pounds"),
                    ("PCS", "Pieces"),
                    ("L", "Liters"),
                    ("M", "Meters"),
                    ("CM", "Centimeters"),
                    ("MM", "Millimeters"),
                    ("SQM", "Square Meters"),
                    ("CU", "Cubic Meters"),
                    ("G", "Grams"),
                    ("MG", "Milligrams"),
                    ("OZ", "Ounces"),
                    ("FL OZ", "Fluid Ounces"),
                    ("GAL", "Gallons"),
                    ("QT", "Quarts"),
                    ("PT", "Pints"),
                    ("YD", "Yards"),
                    ("IN", "Inches"),
                ],
                default="PCS",
                max_length=10,
            ),
        ),
    ]
