# Generated by Django 5.0 on 2023-12-20 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry_name", models.CharField(max_length=100)),
                ("industry_desc", models.TextField()),
                ("hsn_2_digit", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("category_desc", models.TextField()),
                ("hsn_6_digit", models.CharField(max_length=6)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="market.industry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("US", "United States"),
                            ("UK", "United Kingdom"),
                            ("CA", "Canada"),
                            ("FR", "France"),
                            ("DE", "Germany"),
                            ("AF", "Afghanistan"),
                            ("AM", "Armenia"),
                            ("AZ", "Azerbaijan"),
                            ("BH", "Bahrain"),
                            ("BD", "Bangladesh"),
                            ("BT", "Bhutan"),
                            ("BN", "Brunei"),
                            ("KH", "Cambodia"),
                            ("CN", "China"),
                            ("CY", "Cyprus"),
                            ("GE", "Georgia"),
                            ("IN", "India"),
                            ("ID", "Indonesia"),
                            ("IR", "Iran"),
                            ("IQ", "Iraq"),
                            ("IL", "Israel"),
                            ("JP", "Japan"),
                            ("JO", "Jordan"),
                            ("KZ", "Kazakhstan"),
                            ("KW", "Kuwait"),
                            ("KG", "Kyrgyzstan"),
                            ("LA", "Laos"),
                            ("LB", "Lebanon"),
                            ("MO", "Macao"),
                            ("MY", "Malaysia"),
                            ("MV", "Maldives"),
                            ("MN", "Mongolia"),
                            ("MM", "Myanmar"),
                            ("NP", "Nepal"),
                            ("KP", "North Korea"),
                            ("OM", "Oman"),
                            ("PK", "Pakistan"),
                            ("PS", "Palestine"),
                            ("PH", "Philippines"),
                            ("QA", "Qatar"),
                            ("SA", "Saudi Arabia"),
                            ("SG", "Singapore"),
                            ("KR", "South Korea"),
                            ("LK", "Sri Lanka"),
                            ("SY", "Syria"),
                            ("TW", "Taiwan"),
                            ("TJ", "Tajikistan"),
                            ("TH", "Thailand"),
                            ("TL", "Timor-Leste"),
                            ("TR", "Turkey"),
                            ("TM", "Turkmenistan"),
                            ("AE", "United Arab Emirates"),
                            ("UZ", "Uzbekistan"),
                            ("VN", "Vietnam"),
                            ("YE", "Yemen"),
                        ],
                        default="IN",
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post_category",
                    models.ForeignKey(
                        default="000000",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.category",
                    ),
                ),
                (
                    "post_industry",
                    models.ForeignKey(
                        default="00",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.industry",
                    ),
                ),
            ],
        ),
    ]
