# Generated by Django 5.0 on 2024-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="kredtrade.png", upload_to="profile_pics"),
        ),
    ]
