# Generated by Django 5.0 on 2024-01-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="kreditem.png", upload_to="post_pics"),
        ),
    ]
