# Generated by Django 5.0 on 2024-02-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_category",
            field=models.ForeignKey(
                default="000000",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="market.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_industry",
            field=models.ForeignKey(
                default="00",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="market.industry",
            ),
        ),
    ]
