# Generated by Django 5.0 on 2024-02-08 12:06

import django.db.models.deletion
from django.db import migrations, models


def create_intent_instances(apps, schema_editor):
    Intent = apps.get_model('market', 'Intent')  # Adjust 'yourappname' to your actual app name
    intents = ['BUY', 'SELL', 'MERCHANT_EXPORT', 'WHITE_LABEL']
    for intent_name in intents:
        Intent.objects.get_or_create(name=intent_name)


def update_post_intents(apps, schema_editor):
    Post = apps.get_model('market', 'Post')
    Intent = apps.get_model('market', 'Intent')
    for post in Post.objects.all():
        intent_name = post.intent  # Assuming 'intent' was a CharField before
        intent_instance = Intent.objects.get(name=intent_name)
        post.intent = intent_instance  # Now 'intent' should be a ForeignKey to Intent
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_intent_sector_remove_post_country_and_more'),  # Adjust this to your actual previous migration
    ]


    operations = [
        migrations.RunPython(create_intent_instances),
        migrations.RunPython(update_post_intents),
    ]
