# Generated by Django 5.0 on 2024-02-08 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0007_alter_post_intent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="intent",
        ),
    ]
