# Generated by Django 5.0 on 2024-02-08 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0008_remove_post_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="intent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="market.intent",
            ),
        ),
        migrations.AlterField(
            model_name="industry",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="industries",
                to="market.sector",
            ),
        ),
    ]
