# Generated by Django 5.0 on 2024-02-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0009_post_intent_alter_industry_sector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post_category",
        ),
        migrations.AddField(
            model_name="post",
            name="post_category_hsn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="market.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="market.industry",
            ),
        ),
    ]
